from __future__ import annotations

from importlib import import_module


_EXPORT_MAP: dict[str, tuple[str, str]] = {
    "Badge": (".badge", "Badge"),
    "AdaptivePairRow": (".adaptive_pair_row", "AdaptivePairRow"),
    "AssetColumnGuide": (".asset_column_guide", "AssetColumnGuide"),
    "AssetColumnMetrics": (".asset_column_guide", "AssetColumnMetrics"),
    "CalendarMonth": (".calendar_month", "CalendarMonth"),
    "ChatBubble": (".chat_bubble", "ChatBubble"),
    "CommandPalette": (".command_palette", "CommandPalette"),
    "CompactRowActions": (".compact_row_actions", "CompactRowActions"),
    "ContextMenu": (".context_menu", "ContextMenu"),
    "DataTable": (".data_table", "DataTable"),
    "DialogAction": (".dialogs", "DialogAction"),
    "DesignSystemCard": (".design_system_card", "DesignSystemCard"),
    "DetailSummaryCard": (".template_summary_card", "DetailSummaryCard"),
    "DetailSummaryHeader": (".template_summary_header", "DetailSummaryHeader"),
    "DashedSeparator": (".dashed_separator", "DashedSeparator"),
    "DatePicker": (".date_picker", "DatePicker"),
    "Descriptions": (".descriptions", "Descriptions"),
    "DetailPaneController": (".detail_pane_controller", "DetailPaneController"),
    "Divider": (".divider", "Divider"),
    "Drawer": (".drawer", "Drawer"),
    "DynamicNavigationRail": (".dynamic_navigation_rail", "DynamicNavigationRail"),
    "EmptyState": (".empty_state", "EmptyState"),
    "ElidedTextLabel": (".text_projection", "ElidedTextLabel"),
    "ElidedFilenameEdit": (".material_text_views", "ElidedFilenameEdit"),
    "ElidedPathEdit": (".material_text_views", "ElidedPathEdit"),
    "ElidedReadOnlyValue": (
        ".material_text_views",
        "ElidedReadOnlyValue",
    ),
    "ElidedValueEdit": (".material_text_views", "ElidedValueEdit"),
    "ExecutionFeedbackWidget": (".execution_feedback_widget", "ExecutionFeedbackWidget"),
    "ExecutionProgressWidget": (".execution_progress_widget", "ExecutionProgressWidget"),
    "EvidenceActionBar": (".evidence_widgets", "EvidenceActionBar"),
    "EvidenceLineItem": (".evidence_widgets", "EvidenceLineItem"),
    "EvidenceLineList": (".evidence_widgets", "EvidenceLineList"),
    "FeatureToggleRow": (".feature_toggle_row", "FeatureToggleRow"),
    "FileDropZone": (".file_drop_zone", "FileDropZone"),
    "Form": (".form", "Form"),
    "FlowSection": (".flow_section", "FlowSection"),
    "FlowLayout": (".flow_layout", "FlowLayout"),
    "FormActionButtonRow": (".form_action_row", "FormActionButtonRow"),
    "FontCombo": (".font_combo", "FontCombo"),
    "InlineAlert": (".inline_alert", "InlineAlert"),
    "InspectorForm": (".inspector_form", "InspectorForm"),
    "InlineCopyEdit": (".inline_copy_edit", "InlineCopyEdit"),
    "IssueDetailSection": (".issue_detail_section", "IssueDetailSection"),
    "KeyedWidgetListChange": (".keyed_widget_list", "KeyedWidgetListChange"),
    "KeyedWidgetListController": (".keyed_widget_list", "KeyedWidgetListController"),
    "LogStreamWidget": (".log_stream_widget", "LogStreamWidget"),
    "LibraryActionRow": (".library_action_row", "LibraryActionRow"),
    "LicenseDialog": (".license_dialog", "LicenseDialog"),
    "MarkdownPreview": (".markdown_preview", "MarkdownPreview"),
    "MaterialTokenEdit": (".material_token_edit", "MaterialTokenEdit"),
    "MaterialNameEdit": (".material_name_edit", "MaterialNameEdit"),
    "MasterDetailShell": (".master_detail_shell", "MasterDetailShell"),
    "MessageInput": (".message_input", "MessageInput"),
    "ModuleStatusList": (".module_status_list", "ModuleStatusList"),
    "NavigationCard": (".navigation_card", "NavigationCard"),
    "NavigationHighlighter": (".navigation_highlight", "NavigationHighlighter"),
    "NumberingPreset": (".numbering_preset", "NumberingPreset"),
    "OptionToggleChip": (".option_toggle_chip", "OptionToggleChip"),
    "Pagination": (".pagination", "Pagination"),
    "ParagraphStyleEditor": (".paragraph_style_editor", "ParagraphStyleEditor"),
    "PathAcceptancePolicy": (".path_drop", "PathAcceptancePolicy"),
    "PathAction": (".path_action_semantics", "PathAction"),
    "PathActionPresentation": (
        ".path_action_semantics",
        "PathActionPresentation",
    ),
    "PathDropController": (".path_drop", "PathDropController"),
    "PathDropSpec": (".path_drop", "PathDropSpec"),
    "PathProposalResult": (".path_drop", "PathProposalResult"),
    "PathRejectionCode": (".path_drop", "PathRejectionCode"),
    "PersistenceActions": (".persistence_actions", "PersistenceActions"),
    "ProjectedTextEdit": (".projected_text_edit", "ProjectedTextEdit"),
    "ImagePreviewDialog": (".preview_dialog", "ImagePreviewDialog"),
    "PixmapPreviewContent": (".preview_dialog", "PixmapPreviewContent"),
    "PreviewContent": (".preview_dialog", "PreviewContent"),
    "PreviewDialog": (".preview_dialog", "PreviewDialog"),
    "PreviewShellDialog": (".preview_dialog", "PreviewShellDialog"),
    "PreviewItem": (".preview_dialog", "PreviewItem"),
    "TextPreviewDialog": (".preview_dialog", "TextPreviewDialog"),
    "Result": (".result", "Result"),
    "SearchInput": (".search_input", "SearchInput"),
    "SegmentedControl": (".segmented_control", "SegmentedControl"),
    "SizeCombo": (".size_combo", "SizeCombo"),
    "ScrollableDetailGeometrySync": (".detail_geometry", "ScrollableDetailGeometrySync"),
    "SpacingInput": (".spacing_input", "SpacingInput"),
    "Spin": (".spin", "Spin"),
    "SplitPane": (".split_pane", "SplitPane"),
    "StyleEditingSection": (".style_editing_section", "StyleEditingSection"),
    "StyleManagementBlock": (".style_management_block", "StyleManagementBlock"),
    "StyleManagementContentPlan": (".style_management_block", "StyleManagementContentPlan"),
    "StyleManagementContract": (".style_management_block", "StyleManagementContract"),
    "style_management_content_plan": (".style_management_block", "style_management_content_plan"),
    "style_management_contract": (".style_management_block", "style_management_contract"),
    "style_preview_slot_protocol": (".style_management_block", "style_preview_slot_protocol"),
    "StyleObjectProjection": (".style_object_projection", "StyleObjectProjection"),
    "StyleOwnerStatusStrip": (".style_owner_status_strip", "StyleOwnerStatusStrip"),
    "StylePresentationEnvelope": (".style_presentation_envelope", "StylePresentationEnvelope"),
    "StylePreviewSurface": (".style_preview_surface", "StylePreviewSurface"),
    "style_preview_renderer_protocol": (".style_preview_surface", "style_preview_renderer_protocol"),
    "StyleReceiptSlotFrame": (".style_receipt_slot_frame", "StyleReceiptSlotFrame"),
    "StyleResultReceiptRow": (".style_result_receipt_row", "StyleResultReceiptRow"),
    "StyledComboBox": (".styled_combo_box", "StyledComboBox"),
    "StyledSpinBox": (".styled_spin_box", "StyledSpinBox"),
    "SummaryGrid": (".summary_grid", "SummaryGrid"),
    "SummaryGridItem": (".summary_grid", "SummaryGridItem"),
    "SurfaceCard": (".surface_card", "SurfaceCard"),
    "TabBar": (".tab_bar", "TabBar"),
    "TagChip": (".tag_chip", "TagChip"),
    "TemplateFormGrid": (".template_form_layout", "TemplateFormGrid"),
    "TemplateFormStack": (".template_form_layout", "TemplateFormStack"),
    "TemplateSplitColumns": (".template_form_layout", "TemplateSplitColumns"),
    "TemplateSummaryCard": (".template_summary_card", "TemplateSummaryCard"),
    "apply_detail_summary_action_button": (".template_summary_card", "apply_detail_summary_action_button"),
    "attach_path_drop": (".path_drop", "attach_path_drop"),
    "apply_template_summary_action_button": (".template_summary_card", "apply_template_summary_action_button"),
    "TemplateSummaryHeader": (".template_summary_header", "TemplateSummaryHeader"),
    "template_form_pair_row": (".template_form_layout", "template_form_pair_row"),
    "TextArea": (".text_area", "TextArea"),
    "ThemedRadioButton": (".themed_radio_button", "ThemedRadioButton"),
    "ThemedSlider": (".themed_slider", "ThemedSlider"),
    "Toast": (".toast", "Toast"),
    "TokenSectionHeader": (".token_section_header", "TokenSectionHeader"),
    "TokenColumnGuide": (".token_column_guide", "TokenColumnGuide"),
    "TokenColumnMetrics": (".token_column_guide", "TokenColumnMetrics"),
    "GlobalTooltipController": (".tooltip", "GlobalTooltipController"),
    "Typography": (".typography", "Typography"),
    "ViewportMutationTransaction": (".viewport_mutation", "ViewportMutationTransaction"),
    "WidgetPreviewContent": (".preview_dialog", "WidgetPreviewContent"),
    "ZoomablePreviewViewport": (".preview_dialog", "ZoomablePreviewViewport"),
    "TypingIndicator": (".typing_indicator", "TypingIndicator"),
    "apply_button_variant": (".button_style", "apply_button_variant"),
    "apply_compact_row_action": (".compact_row_actions", "apply_compact_row_action"),
    "compact_row_actions_width": (".compact_row_actions", "compact_row_actions_width"),
    "bind_theme": (".theme", "bind_theme"),
    "build_button_stylesheet": (".button_style", "build_button_stylesheet"),
    "build_checkbox_stylesheet": (".selection_control_style", "build_checkbox_stylesheet"),
    "build_text_input_stylesheet": (".input_style", "build_text_input_stylesheet"),
    "disable_global_tooltip": (".tooltip", "disable_global_tooltip"),
    "confirm": (".dialogs", "confirm"),
    "decision": (".dialogs", "decision"),
    "dialog_error": (".dialogs", "error"),
    "dialog_info": (".dialogs", "info"),
    "dialog_input_text": (".dialogs", "input_text"),
    "dialog_success": (".dialogs", "success"),
    "dialog_warning": (".dialogs", "warning"),
    "install_global_tooltip": (".tooltip", "install_global_tooltip"),
    "resolved_control_height": (".sizing", "resolved_control_height"),
    "resolve_asset_column_metrics": (".asset_column_guide", "resolve_asset_column_metrics"),
    "set_global_tooltip": (".tooltip", "set_global_tooltip"),
    "template_form_row": (".template_form_layout", "template_form_row"),
    "apply_token_row_style": (".token_row_style", "apply_token_row_style"),
    "build_token_row_stylesheet": (
        ".token_row_style",
        "build_token_row_stylesheet",
    ),
    "tooltip_position_for": (".tooltip", "tooltip_position_for"),
    "resolve_token_column_metrics": (".token_column_guide", "resolve_token_column_metrics"),
    "viewport_mutation": (".viewport_mutation", "viewport_mutation"),
    "viewport_mutation_for_widget": (".viewport_mutation", "viewport_mutation_for_widget"),
}

__all__ = list(_EXPORT_MAP)


def __getattr__(name: str):
    try:
        module_name, attr_name = _EXPORT_MAP[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc

    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(list(globals().keys()) + list(__all__))
