from __future__ import annotations

from importlib import import_module


_EXPORT_MAP: dict[str, tuple[str, str]] = {
    "Badge": (".badge", "Badge"),
    "AdaptivePairRow": (".adaptive_pair_row", "AdaptivePairRow"),
    "CalendarMonth": (".calendar_month", "CalendarMonth"),
    "ChatBubble": (".chat_bubble", "ChatBubble"),
    "CommandPalette": (".command_palette", "CommandPalette"),
    "ConfigListWidget": (".config_list_widget", "ConfigListWidget"),
    "ContextMenu": (".context_menu", "ContextMenu"),
    "DataTable": (".data_table", "DataTable"),
    "DesignSystemCard": (".design_system_card", "DesignSystemCard"),
    "DetailSummaryCard": (".template_summary_card", "DetailSummaryCard"),
    "DetailSummaryHeader": (".template_summary_header", "DetailSummaryHeader"),
    "DashedSeparator": (".dashed_separator", "DashedSeparator"),
    "DatePicker": (".date_picker", "DatePicker"),
    "Descriptions": (".descriptions", "Descriptions"),
    "DetailPaneController": (".detail_pane_controller", "DetailPaneController"),
    "Divider": (".divider", "Divider"),
    "Drawer": (".drawer", "Drawer"),
    "DynamicNavigationRail": (".dynamic_navigation_rail", "DynamicNavigationRail"),
    "EmptyState": (".empty_state", "EmptyState"),
    "ExecutionFeedbackWidget": (".execution_feedback_widget", "ExecutionFeedbackWidget"),
    "ExecutionProgressWidget": (".execution_progress_widget", "ExecutionProgressWidget"),
    "EvidenceActionBar": (".evidence_widgets", "EvidenceActionBar"),
    "EvidenceLineItem": (".evidence_widgets", "EvidenceLineItem"),
    "EvidenceLineList": (".evidence_widgets", "EvidenceLineList"),
    "FeatureToggleRow": (".feature_toggle_row", "FeatureToggleRow"),
    "FileDropZone": (".file_drop_zone", "FileDropZone"),
    "Form": (".form", "Form"),
    "FlowSection": (".flow_section", "FlowSection"),
    "FlowLayout": (".flow_layout", "FlowLayout"),
    "FormActionButtonRow": (".form_action_row", "FormActionButtonRow"),
    "FontCombo": (".font_combo", "FontCombo"),
    "InlineAlert": (".inline_alert", "InlineAlert"),
    "InspectorForm": (".inspector_form", "InspectorForm"),
    "IssueDetailSection": (".issue_detail_section", "IssueDetailSection"),
    "LogStreamWidget": (".log_stream_widget", "LogStreamWidget"),
    "LibraryActionRow": (".library_action_row", "LibraryActionRow"),
    "MarkdownPreview": (".markdown_preview", "MarkdownPreview"),
    "MasterDetailShell": (".master_detail_shell", "MasterDetailShell"),
    "MessageInput": (".message_input", "MessageInput"),
    "ModuleStatusList": (".module_status_list", "ModuleStatusList"),
    "NavigationCard": (".navigation_card", "NavigationCard"),
    "NavigationHighlighter": (".navigation_highlight", "NavigationHighlighter"),
    "NumberingPreset": (".numbering_preset", "NumberingPreset"),
    "OptionToggleChip": (".option_toggle_chip", "OptionToggleChip"),
    "Pagination": (".pagination", "Pagination"),
    "ParagraphStyleEditor": (".paragraph_style_editor", "ParagraphStyleEditor"),
    "Result": (".result", "Result"),
    "SearchInput": (".search_input", "SearchInput"),
    "SegmentedControl": (".segmented_control", "SegmentedControl"),
    "SizeCombo": (".size_combo", "SizeCombo"),
    "ScrollableDetailGeometrySync": (".detail_geometry", "ScrollableDetailGeometrySync"),
    "SpacingInput": (".spacing_input", "SpacingInput"),
    "Spin": (".spin", "Spin"),
    "SplitPane": (".split_pane", "SplitPane"),
    "StyleDifferenceSummarySlot": (".style_difference_summary_slot", "StyleDifferenceSummarySlot"),
    "StyleEditingSection": (".style_editing_section", "StyleEditingSection"),
    "StyleComparisonStrip": (".style_comparison_strip", "StyleComparisonStrip"),
    "StyleManagementBlock": (".style_management_block", "StyleManagementBlock"),
    "StyleManagementContentPlan": (".style_management_block", "StyleManagementContentPlan"),
    "StyleManagementContract": (".style_management_block", "StyleManagementContract"),
    "style_management_content_plan": (".style_management_block", "style_management_content_plan"),
    "style_management_contract": (".style_management_block", "style_management_contract"),
    "style_preview_slot_protocol": (".style_management_block", "style_preview_slot_protocol"),
    "StyleObjectProjection": (".style_object_projection", "StyleObjectProjection"),
    "StyleOwnerStatusStrip": (".style_owner_status_strip", "StyleOwnerStatusStrip"),
    "StylePresentationEnvelope": (".style_presentation_envelope", "StylePresentationEnvelope"),
    "StylePreviewSurface": (".style_preview_surface", "StylePreviewSurface"),
    "style_preview_renderer_protocol": (".style_preview_surface", "style_preview_renderer_protocol"),
    "StyleReceiptSlotFrame": (".style_receipt_slot_frame", "StyleReceiptSlotFrame"),
    "StyleResultReceiptRow": (".style_result_receipt_row", "StyleResultReceiptRow"),
    "StylePolicyActionProjection": (".style_policy_control_deck", "StylePolicyActionProjection"),
    "StylePolicyControlDeck": (".style_policy_control_deck", "StylePolicyControlDeck"),
    "StylePolicyProjection": (".style_policy_control_deck", "StylePolicyProjection"),
    "style_policy_control_protocol": (".style_policy_control_deck", "style_policy_control_protocol"),
    "StylePolicyToggleList": (".style_policy_toggle_list", "StylePolicyToggleList"),
    "StylePolicyToggleOption": (".style_policy_toggle_list", "StylePolicyToggleOption"),
    "StylePolicyToggleProjection": (".style_policy_control_deck", "StylePolicyToggleProjection"),
    "StyleRuleControlDeck": (".style_rule_control_deck", "StyleRuleControlDeck"),
    "StyleSourceCompactRow": (".style_source_compact_row", "StyleSourceCompactRow"),
    "StyleSourceSlot": (".style_source_slot", "StyleSourceSlot"),
    "StyledComboBox": (".styled_combo_box", "StyledComboBox"),
    "StyledSpinBox": (".styled_spin_box", "StyledSpinBox"),
    "SummaryGrid": (".summary_grid", "SummaryGrid"),
    "SummaryGridItem": (".summary_grid", "SummaryGridItem"),
    "SurfaceCard": (".surface_card", "SurfaceCard"),
    "TabBar": (".tab_bar", "TabBar"),
    "TagChip": (".tag_chip", "TagChip"),
    "TemplateFormGrid": (".template_form_layout", "TemplateFormGrid"),
    "TemplateFormStack": (".template_form_layout", "TemplateFormStack"),
    "TemplateSplitColumns": (".template_form_layout", "TemplateSplitColumns"),
    "TemplateSummaryCard": (".template_summary_card", "TemplateSummaryCard"),
    "apply_detail_summary_action_button": (".template_summary_card", "apply_detail_summary_action_button"),
    "apply_template_summary_action_button": (".template_summary_card", "apply_template_summary_action_button"),
    "TemplateSummaryHeader": (".template_summary_header", "TemplateSummaryHeader"),
    "template_form_pair_row": (".template_form_layout", "template_form_pair_row"),
    "TextArea": (".text_area", "TextArea"),
    "ThemedRadioButton": (".themed_radio_button", "ThemedRadioButton"),
    "ThemedSlider": (".themed_slider", "ThemedSlider"),
    "Toast": (".toast", "Toast"),
    "GlobalTooltipController": (".tooltip", "GlobalTooltipController"),
    "Typography": (".typography", "Typography"),
    "TypingIndicator": (".typing_indicator", "TypingIndicator"),
    "apply_button_variant": (".button_style", "apply_button_variant"),
    "bind_theme": (".theme", "bind_theme"),
    "build_button_stylesheet": (".button_style", "build_button_stylesheet"),
    "build_checkbox_stylesheet": (".selection_control_style", "build_checkbox_stylesheet"),
    "build_text_input_stylesheet": (".input_style", "build_text_input_stylesheet"),
    "install_global_tooltip": (".tooltip", "install_global_tooltip"),
    "normalize_form_control_heights": (".sizing", "normalize_form_control_heights"),
    "resolved_control_height": (".sizing", "resolved_control_height"),
    "set_global_tooltip": (".tooltip", "set_global_tooltip"),
    "template_form_row": (".template_form_layout", "template_form_row"),
    "tooltip_position_for": (".tooltip", "tooltip_position_for"),
}

__all__ = list(_EXPORT_MAP)


def __getattr__(name: str):
    try:
        module_name, attr_name = _EXPORT_MAP[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc

    module = import_module(module_name, __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(list(globals().keys()) + list(__all__))
