"""Source evidence definitions for the scene matrix drilldown."""

from __future__ import annotations

from src.config.scene_release_governance_registry import (
    scene_release_governance_drilldown_source_marker_entries,
)

SCENE_MATRIX_DRILLDOWN_SOURCE_ID = "scene_matrix_drilldown"
SCENE_MATRIX_DRILLDOWN_RUNTIME_SOURCE_PATH = "src/config/scene_matrix_drilldown.py"
SCENE_MATRIX_DRILLDOWN_AUDIT_DOCS_PATH = "docs/audits"
SCENE_MATRIX_DRILLDOWN_CONFIG_SOURCE_PATH = "src/config"
SCENE_MATRIX_DRILLDOWN_RELEASE_ITEMS_SOURCE_PATH = (
    "src/config/scene_matrix_drilldown_release_items.py"
)
SCENE_MATRIX_DRILLDOWN_EXPORT_SCRIPT_SOURCE_PATH = (
    "scripts/export_scene_matrix_drilldown.py"
)
SCENE_MATRIX_DRILLDOWN_SUMMARY_PROJECTION_SOURCE_PATH = (
    "src/ui/panels/scene_summary_projection.py"
)
SCENE_MATRIX_DRILLDOWN_TEST_SOURCE_PATH = (
    "tests/test_scene_matrix_drilldown_frontend_sources.py"
)


def _drilldown_runtime_source_marker_entry(
    source_id: str,
    *markers: str,
) -> tuple[str, str, tuple[str, ...]]:
    return (source_id, SCENE_MATRIX_DRILLDOWN_RUNTIME_SOURCE_PATH, markers)


def _drilldown_audit_doc_source_marker_entry(
    source_id: str,
    doc_filename: str,
    *markers: str,
) -> tuple[str, str, tuple[str, ...]]:
    return (
        source_id,
        f"{SCENE_MATRIX_DRILLDOWN_AUDIT_DOCS_PATH}/{doc_filename}",
        markers,
    )


def _scene_config_source_marker_entry(
    source_id: str,
    *markers: str,
) -> tuple[str, str, tuple[str, ...]]:
    return (
        source_id,
        f"{SCENE_MATRIX_DRILLDOWN_CONFIG_SOURCE_PATH}/{source_id}.py",
        markers,
    )


REQUIRED_SCENE_MATRIX_DRILLDOWN_IDS: tuple[str, ...] = (
    "matrix_dashboard",
    "request_cells",
    "ambiguity_clarification",
    "user_journey_fixture",
    "business_capability_matrix",
    "control_runtime_consistency",
    "plugin_boundary",
    "external_handoff_contract",
    "boundary_guarded_completion",
    "residual_warning_governance",
    "boundary_readiness_reconciliation",
    "terminal_release_exception",
    "boundary_subject_release_dossier",
    "non_subject_release_trace_attribution",
    "release_trace_partition_guard",
    "release_projection_surface_parity",
    "boundary_subject_release_continuity",
    "release_closure_ledger",
    "boundary_maturity_release_envelope",
    "retained_gap_exit_criteria",
    "release_residual_ratio_ledger",
    "release_residual_explanation",
    "release_acceptance_certificate",
    "word_risk",
    "import_handoff",
    "input_source",
    "object_preflight_action",
    "family_fixture_depth",
    "count_profile",
    "material_schema",
    "material_repair_flow",
    "fixed_layout_profile",
    "report_artifact_drilldown",
    "delivery_preset",
    "delivery_execution",
    "formula_output_watermark",
    "maturity_upgrade",
)

SCENE_MATRIX_DRILLDOWN_SOURCE_MARKERS: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    _scene_config_source_marker_entry(
        "scene_matrix_dashboard",
        "build_scene_matrix_dashboard",
        "SCENE_MATRIX_DASHBOARD_LENSES",
    ),
    (
        "scene_request_cell_registry_browser",
        "src/config/scene_request_cell_fixture_registry.py",
        ("build_scene_request_cell_registry_browser", "SceneRequestCellBrowserItem"),
    ),
    _scene_config_source_marker_entry(
        "scene_ambiguity_clarification_ui_audit",
        "build_scene_ambiguity_clarification_ui_audit_report",
        "SceneAmbiguityClarificationRow",
    ),
    _scene_config_source_marker_entry(
        "scene_user_journey_fixture_audit",
        "build_scene_user_journey_fixture_audit_report",
        "SceneUserJourneyPathRow",
    ),
    _scene_config_source_marker_entry(
        "scene_external_handoff_contract_audit",
        "build_scene_external_handoff_contract_audit_report",
        "SceneExternalHandoffContractRow",
    ),
    *scene_release_governance_drilldown_source_marker_entries(),
    (
        "scene_matrix_drilldown_acceptance_receipt_projection",
        SCENE_MATRIX_DRILLDOWN_RELEASE_ITEMS_SOURCE_PATH,
        (
            "_release_acceptance_certificate_item",
            "acceptance_receipt_trace",
            "release_residual_ratio_receipts",
            "retained_gap_external_receipts",
        ),
    ),
    (
        "scene_matrix_drilldown_residual_receipt_projection",
        SCENE_MATRIX_DRILLDOWN_RELEASE_ITEMS_SOURCE_PATH,
        (
            "_release_residual_receipt_detail",
            "receipt_alignments=",
            "count_delivery_receipts=",
            "maturity_l5_receipts=",
        ),
    ),
    (
        "scene_matrix_drilldown_export_receipt_projection",
        SCENE_MATRIX_DRILLDOWN_EXPORT_SCRIPT_SOURCE_PATH,
        (
            "_report_markdown",
            "json.dumps(report.to_payload()",
            "item.detail",
            "row.detail",
        ),
    ),
    (
        "scene_matrix_drilldown_export_source_summary_projection",
        SCENE_MATRIX_DRILLDOWN_EXPORT_SCRIPT_SOURCE_PATH,
        (
            "Source evidence:",
            "ready_source_evidence_count",
            "missing_source_evidence_count",
        ),
    ),
    (
        "scene_matrix_drilldown_export_json_source_summary_projection",
        SCENE_MATRIX_DRILLDOWN_EXPORT_SCRIPT_SOURCE_PATH,
        (
            "json.dumps(report.to_payload()",
            "ensure_ascii=False",
            "indent=2",
        ),
    ),
    (
        "scene_matrix_drilldown_source_evidence_payload_consistency_tests",
        SCENE_MATRIX_DRILLDOWN_TEST_SOURCE_PATH,
        (
            'len(payload["source_evidence"])',
            'payload["counts"]["source_evidence_count"]',
            'payload["counts"]["ready_source_evidence_count"]',
        ),
    ),
    (
        "scene_matrix_drilldown_source_evidence_unique_id_tests",
        SCENE_MATRIX_DRILLDOWN_TEST_SOURCE_PATH,
        (
            "report_source_ids",
            "payload_source_ids",
            "set(report_source_ids)",
        ),
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_item_row_identity_audit",
        "duplicate_drilldown_id",
        "duplicate_row_id",
        "seen_row_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_item_source_evidence_audit",
        "missing_item_source_evidence",
        "evidence_source_ids",
        "item_source_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_row_source_evidence_audit",
        "missing_row_source_evidence",
        "row_source_mismatch",
        "row_source_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_row_pack_family_registry_audit",
        "unknown_row_pack_id",
        "unknown_row_family_id",
        "coverage_pack_ids",
        "planned_family_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_row_request_fixture_registry_audit",
        "unknown_row_request_cell_id",
        "unknown_row_fixture_id",
        "request_cell_ids",
        "sample_fixture_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_row_count_delivery_registry_audit",
        "unknown_row_count_profile_id",
        "unknown_row_delivery_reference_id",
        "count_profile_ids",
        "delivery_reference_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_row_material_reference_audit",
        "unknown_row_material_reference_id",
        "material_reference_ids",
        "material_schema_ids",
        "row.material_schema_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_row_input_object_word_registry_audit",
        "unknown_row_input_source_id",
        "unknown_row_render_source_id",
        "unknown_row_object_preflight_target_id",
        "unknown_row_word_risk_surface_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_row_plugin_risk_maturity_registry_audit",
        "unknown_row_plugin_gate_id",
        "unknown_row_risk_domain_id",
        "unknown_row_maturity_gap_reference_id",
        "plugin_gate_reference_ids",
        "maturity_gap_reference_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_action_capability_projection_profile_audit",
        "SCENE_MATRIX_DRILLDOWN_PROJECTION_PROFILES",
        "SceneMatrixDrilldownProjectionProfile",
        "missing_action_behavior_projection_profile",
        "missing_capability_projection_profile",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_test_reference_audit",
        "unknown_projection_test_reference_id",
        "_projection_test_reference_ids",
        "action_behavior_ids",
        "capability_ids",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_source_reference_audit",
        "_projection_source_reference_map",
        "_projection_source_reference_ids",
        "missing_projection_source_reference_id",
        "unknown_projection_source_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_surface_reference_audit",
        "_projection_surface_reference_map",
        "projection_surface_reference_map",
        "missing_projection_surface_reference_id",
        "surface_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_path_reference_audit",
        "_projection_path_reference_map",
        "projection_path_reference_map",
        "missing_projection_path_reference_id",
        "missing_projection_path_file",
        "path_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_evidence_reference_audit",
        "_projection_evidence_reference_map",
        "projection_evidence_reference_map",
        "missing_projection_evidence_reference_id",
        "evidence_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_release_marker_reference_audit",
        "_projection_release_marker_reference_map",
        "projection_release_marker_reference_map",
        "missing_projection_release_marker_reference_id",
        "marker_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_release_link_reference_audit",
        "_projection_release_link_reference_map",
        "projection_release_link_reference_map",
        "missing_projection_release_link_reference_id",
        "link_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_retained_gap_exit_reference_audit",
        "_projection_retained_gap_exit_reference_map",
        "projection_retained_gap_exit_reference_map",
        "missing_projection_retained_gap_exit_",
        "retained_gap_exit_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_control_runtime_reference_audit",
        "_projection_control_runtime_reference_map",
        "projection_control_runtime_reference_map",
        "missing_projection_control_runtime_",
        "control_runtime_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_release_metric_reference_audit",
        "_projection_release_metric_reference_map",
        "projection_release_metric_reference_map",
        "missing_projection_release_metric_reference_id",
        "release_metric_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_external_handoff_reference_audit",
        "_projection_external_handoff_contract_reference_map",
        "projection_external_handoff_contract_reference_map",
        "missing_projection_external_handoff_",
        "unknown_projection_external_handoff_",
        "handoff_contract_reference_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_report_delivery_marker_audit",
        "_projection_report_delivery_marker_reference_map",
        "projection_report_delivery_marker_reference_map",
        "missing_projection_report_delivery_",
        "report_delivery_marker_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_requirement_dimension_reference_audit",
        "_projection_requirement_dimension_reference_map",
        "missing_projection_requirement_dimension_reference_id",
        "projection_requirement_dimension_reference_map",
        "dimension_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_target_plugin_reference_audit",
        "_target_plugin_reference_ids",
        "_projection_target_plugin_reference_map",
        "projection_target_plugin_reference_map",
        "missing_projection_target_plugin_reference_id",
        "unknown_projection_target_plugin_reference_id",
        "target_plugin_id",
    ),
    _drilldown_runtime_source_marker_entry(
        "scene_matrix_drilldown_projection_formula_output_watermark_reference_audit",
        "_projection_formula_output_watermark_reference_map",
        "projection_formula_output_watermark_reference_map",
        "missing_projection_formula_output_",
        "formula_output_watermark_reference_id",
    ),
    (
        "scene_matrix_drilldown_source_summary_projection",
        SCENE_MATRIX_DRILLDOWN_SUMMARY_PROJECTION_SOURCE_PATH,
        (
            "build_scene_matrix_drilldown_summary_items",
            "scene_matrix_drilldown_sources",
            "report.source_evidence",
        ),
    ),
    (
        "scene_matrix_drilldown_source_summary_readiness_projection",
        SCENE_MATRIX_DRILLDOWN_SUMMARY_PROJECTION_SOURCE_PATH,
        (
            "ready_source_evidence_count",
            "source_evidence_count",
            "missing_source_evidence_count",
        ),
    ),
    (
        "scene_matrix_drilldown_release_gate_source_summary_projection",
        "scripts/verify_scene_matrix_release_gate.py",
        (
            "scene_matrix_drilldown_source_evidence_count",
            "scene_matrix_drilldown_ready_source_evidence_count",
            "drilldown_sources=",
        ),
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_402_acceptance_drilldown_trace_plan",
        "scene_release_acceptance_drilldown_trace_N2_402_2026-06-25.md",
        "N2.402",
        "acceptance_receipt_trace",
        "release_residual_ratio_receipts",
        "retained_gap_external_receipts",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_407_residual_receipt_drilldown_plan",
        "scene_release_residual_receipt_drilldown_trace_N2_407_2026-06-25.md",
        "N2.407",
        "receipt_alignments=2/2",
        "maturity_l5_receipts=6/6",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_408_residual_receipt_export_plan",
        "scene_release_residual_receipt_export_trace_N2_408_2026-06-25.md",
        "N2.408",
        "item.detail",
        "row.detail",
        "maturity_l5_receipts=6/6",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_409_residual_receipt_source_summary_plan",
        "scene_release_residual_receipt_source_summary_trace_N2_409_2026-06-25.md",
        "N2.409",
        "scene_matrix_drilldown_export_receipt_projection",
        "n2_408_residual_receipt_export_plan",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_410_drilldown_source_evidence_release_summary_plan",
        "scene_matrix_drilldown_source_evidence_release_summary_trace_N2_410_2026-06-25.md",
        "N2.410",
        "Release Gate terminal summary",
        "source evidence readiness",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_411_drilldown_source_summary_ready_total_plan",
        "scene_matrix_drilldown_source_summary_ready_total_trace_N2_411_2026-06-25.md",
        "N2.411",
        "Summary card",
        "ready/total",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_412_drilldown_export_source_summary_plan",
        "scene_matrix_drilldown_export_source_summary_trace_N2_412_2026-06-25.md",
        "N2.412",
        "Markdown export",
        "source evidence readiness",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_413_drilldown_json_export_source_summary_plan",
        "scene_matrix_drilldown_json_export_source_summary_trace_N2_413_2026-06-25.md",
        "N2.413",
        "JSON export",
        "source evidence readiness",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_414_drilldown_source_evidence_payload_consistency_plan",
        "scene_matrix_drilldown_source_evidence_payload_consistency_trace_N2_414_2026-06-25.md",
        "N2.414",
        "payload list length",
        "55/55",
        "0 missing",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_415_drilldown_source_evidence_unique_id_plan",
        "scene_matrix_drilldown_source_evidence_unique_id_trace_N2_415_2026-06-25.md",
        "N2.415",
        "unique source_id",
        "57/57",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_416_drilldown_item_row_unique_id_plan",
        "scene_matrix_drilldown_item_row_unique_id_trace_N2_416_2026-06-25.md",
        "N2.416",
        "unique drilldown_id",
        "unique row_id",
        "59/59",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_417_drilldown_item_source_evidence_trace_plan",
        "scene_matrix_drilldown_item_source_evidence_trace_N2_417_2026-06-25.md",
        "N2.417",
        "item.source_id",
        "source evidence",
        "61/61",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_418_drilldown_row_source_evidence_trace_plan",
        "scene_matrix_drilldown_row_source_evidence_trace_N2_418_2026-06-25.md",
        "N2.418",
        "row.source_id",
        "row_source_mismatch",
        "63/63",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_419_drilldown_row_pack_family_registry_trace_plan",
        "scene_matrix_drilldown_row_pack_family_registry_trace_N2_419_2026-06-25.md",
        "N2.419",
        "pack_ids",
        "family_ids",
        "65/65",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_420_drilldown_row_request_fixture_registry_trace_plan",
        "scene_matrix_drilldown_row_request_fixture_registry_trace_N2_420_2026-06-25.md",
        "N2.420",
        "request_cell_ids",
        "fixture_ids",
        "67/67",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_421_drilldown_row_count_delivery_registry_trace_plan",
        "scene_matrix_drilldown_row_count_delivery_registry_trace_N2_421_2026-06-25.md",
        "N2.421",
        "count_profile_ids",
        "delivery_preset_ids",
        "69/69",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_422_drilldown_row_material_reference_trace_plan",
        "scene_matrix_drilldown_row_material_reference_trace_N2_422_2026-06-25.md",
        "N2.422",
        "material_schema_ids",
        "material_reference_ids",
        "71/71",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_423_drilldown_row_input_object_word_registry_trace_plan",
        "scene_matrix_drilldown_row_input_object_word_registry_trace_N2_423_2026-06-25.md",
        "N2.423",
        "input_source_ids",
        "object_preflight_target_ids",
        "word_risk_surface_ids",
        "73/73",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_424_drilldown_row_plugin_risk_maturity_registry_trace_plan",
        "scene_matrix_drilldown_row_plugin_risk_maturity_registry_trace_N2_424_2026-06-25.md",
        "N2.424",
        "plugin_gate_ids",
        "risk_domain_ids",
        "maturity_gap_domain_ids",
        "75/75",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_425_drilldown_action_capability_projection_profile_trace_plan",
        "scene_matrix_drilldown_action_capability_projection_profile_trace_N2_425_2026-06-25.md",
        "N2.425",
        "action_behavior_ids",
        "capability_ids",
        "77/77",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_426_drilldown_projection_test_reference_trace_plan",
        "scene_matrix_drilldown_projection_test_reference_trace_N2_426_2026-06-25.md",
        "N2.426",
        "test_ids",
        "action_behavior_ids",
        "79/79",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_427_drilldown_projection_source_reference_trace_plan",
        "scene_matrix_drilldown_projection_source_reference_trace_N2_427_2026-06-25.md",
        "N2.427",
        "source_ids",
        "missing_projection_source_reference_id",
        "81/81",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_428_drilldown_projection_surface_reference_trace_plan",
        "scene_matrix_drilldown_projection_surface_reference_trace_N2_428_2026-06-26.md",
        "N2.428",
        "runtime_surface_ids",
        "missing_projection_surface_reference_id",
        "83/83",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_429_drilldown_projection_path_reference_trace_plan",
        "scene_matrix_drilldown_projection_path_reference_trace_N2_429_2026-06-26.md",
        "N2.429",
        "export_script_path",
        "missing_projection_path_reference_id",
        "85/85",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_430_drilldown_projection_evidence_reference_trace_plan",
        "scene_matrix_drilldown_projection_evidence_reference_trace_N2_430_2026-06-26.md",
        "N2.430",
        "evidence_ids",
        "missing_projection_evidence_reference_id",
        "87/87",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_431_drilldown_projection_release_marker_trace_plan",
        "scene_matrix_drilldown_projection_release_marker_trace_N2_431_2026-06-26.md",
        "N2.431",
        "release_gate_check_id",
        "missing_projection_release_marker_reference_id",
        "89/89",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_432_drilldown_projection_release_link_trace_plan",
        "scene_matrix_drilldown_projection_release_link_trace_N2_432_2026-06-26.md",
        "N2.432",
        "upstream_stage_ids",
        "missing_projection_release_link_reference_id",
        "91/91",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_433_drilldown_projection_retained_gap_exit_reference_trace_plan",
        "scene_matrix_drilldown_projection_retained_gap_exit_reference_trace_N2_433_2026-06-26.md",
        "N2.433",
        "external_handoff_contract_id",
        "missing_projection_retained_gap_exit_reference_id",
        "93/93",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_434_drilldown_projection_control_runtime_reference_trace_plan",
        "scene_matrix_drilldown_projection_control_runtime_reference_trace_N2_434_2026-06-26.md",
        "N2.434",
        "template_surface_ids",
        "missing_projection_control_runtime_reference_id",
        "95/95",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_435_drilldown_projection_release_metric_reference_trace_plan",
        "scene_matrix_drilldown_projection_release_metric_reference_trace_N2_435_2026-06-26.md",
        "N2.435",
        "receipt_alignments=",
        "missing_projection_release_metric_reference_id",
        "97/97",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_436_drilldown_projection_external_handoff_reference_trace_plan",
        "scene_matrix_drilldown_projection_external_handoff_reference_trace_N2_436_2026-06-26.md",
        "N2.436",
        "external_handoff_contract_ids",
        "missing_projection_external_handoff_contract_reference_id",
        "99/99",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_437_drilldown_projection_report_delivery_marker_trace_plan",
        "scene_matrix_drilldown_projection_report_delivery_marker_trace_N2_437_2026-06-26.md",
        "N2.437",
        "artifact_kind_ids",
        "missing_projection_report_delivery_marker_reference_id",
        "101/101",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_438_drilldown_projection_requirement_dimension_trace_plan",
        "scene_matrix_drilldown_projection_requirement_dimension_trace_N2_438_2026-06-26.md",
        "N2.438",
        "requirement_dimension_ids",
        "missing_projection_requirement_dimension_reference_id",
        "103/103",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_439_drilldown_projection_target_plugin_trace_plan",
        "scene_matrix_drilldown_projection_target_plugin_trace_N2_439_2026-06-26.md",
        "N2.439",
        "target_plugin_ids",
        "missing_projection_target_plugin_reference_id",
        "105/105",
    ),
    _drilldown_audit_doc_source_marker_entry(
        "n2_440_drilldown_projection_formula_output_watermark_trace_plan",
        "scene_matrix_drilldown_projection_formula_output_watermark_trace_N2_440_2026-06-26.md",
        "N2.440",
        "parameter_paths",
        "missing_projection_formula_output_watermark_reference_id",
        "107/107",
    ),
    _scene_config_source_marker_entry(
        "scene_business_capability_matrix_audit",
        "build_scene_business_capability_matrix_audit_report",
        "SceneBusinessCapabilityRow",
    ),
    _scene_config_source_marker_entry(
        "scene_control_runtime_consistency_audit",
        "build_scene_control_runtime_consistency_audit_report",
        "SceneControlRuntimeRow",
    ),
    _scene_config_source_marker_entry(
        "scene_plugin_boundary_confirmation_audit",
        "build_scene_plugin_boundary_confirmation_audit_report",
        "ScenePluginBoundaryConfirmationRow",
    ),
    _scene_config_source_marker_entry(
        "scene_word_risk_closure_audit",
        "build_scene_word_risk_closure_audit_report",
        "SceneWordRiskClosureRow",
    ),
    _scene_config_source_marker_entry(
        "scene_import_handoff_audit",
        "build_scene_import_handoff_audit_report",
        "SceneImportHandoffRow",
    ),
    _scene_config_source_marker_entry(
        "scene_input_source_audit",
        "build_scene_input_source_audit_report",
        "SceneInputSourceFamilyRow",
    ),
    _scene_config_source_marker_entry(
        "scene_object_preflight_action_audit",
        "build_scene_object_preflight_action_audit_report",
        "SceneObjectPreflightTargetRow",
    ),
    _scene_config_source_marker_entry(
        "scene_family_fixture_depth_audit",
        "build_scene_family_fixture_depth_audit_report",
        "SceneFamilyFixtureDepthRow",
    ),
    _scene_config_source_marker_entry(
        "scene_count_profile_audit",
        "build_scene_count_profile_audit_report",
        "SceneCountProfileFamilyRow",
    ),
    _scene_config_source_marker_entry(
        "scene_material_schema_audit",
        "build_scene_material_schema_audit_report",
        "SceneMaterialSchemaFamilyRow",
    ),
    _scene_config_source_marker_entry(
        "scene_material_repair_flow_audit",
        "build_scene_material_repair_flow_audit_report",
        "SceneMaterialRepairFlowRow",
    ),
    _scene_config_source_marker_entry(
        "scene_fixed_layout_profile_audit",
        "build_scene_fixed_layout_profile_audit_report",
        "SceneFixedLayoutProfileRow",
    ),
    _scene_config_source_marker_entry(
        "scene_report_artifact_drilldown_audit",
        "build_scene_report_artifact_drilldown_audit_report",
        "SceneReportArtifactDrilldownRow",
    ),
    _scene_config_source_marker_entry(
        "scene_delivery_preset_audit",
        "build_scene_delivery_preset_audit_report",
        "SceneDeliveryPresetFamilyRow",
    ),
    _scene_config_source_marker_entry(
        "scene_delivery_preset_execution_audit",
        "build_scene_delivery_preset_execution_audit_report",
        "SceneDeliveryPresetExecutionRow",
    ),
    _scene_config_source_marker_entry(
        "scene_formula_output_watermark_audit",
        "build_scene_formula_output_watermark_audit_report",
        "SceneFormulaOutputWatermarkFamilyRow",
    ),
    _scene_config_source_marker_entry(
        "scene_product_maturity_upgrade_audit",
        "build_scene_product_maturity_upgrade_audit_report",
        "SceneProductMaturityUpgradeRow",
    ),
)


__all__ = [
    "REQUIRED_SCENE_MATRIX_DRILLDOWN_IDS",
    "SCENE_MATRIX_DRILLDOWN_SOURCE_ID",
    "SCENE_MATRIX_DRILLDOWN_SOURCE_MARKERS",
]
