"""Compatibility exports for local question-figure material helpers.

The implementation now lives in ``src.services.material_assets.question_figures``.
Keep this module so existing assets-panel imports remain stable while new code
can depend on the service layer directly.
"""

from __future__ import annotations

from src.services.material_assets.question_figures import (
    _asset_item_alt_text,
    _asset_item_cached_path,
    _asset_item_library_asset_id,
    _asset_item_preview_path,
    _asset_item_preview_reference,
    _asset_item_source,
    _asset_item_thumbnail_path,
    _question_figure_asset_items,
    _question_figure_asset_sort_key,
    _question_figure_candidate_list,
    _question_figure_collection_summary,
    _question_figure_compare_display_name,
    _question_figure_compare_index_label,
    _question_figure_compare_options,
    _question_figure_detail_rows,
    _question_figure_item_matches_repair_target,
    _question_figure_item_summary,
    _question_figure_order_value,
    _question_figure_payload_matches_item,
    _question_figure_repair_target_payload,
    _question_figure_target_cache_path,
    _question_figure_target_label,
    _question_figure_target_value,
    asset_item_alt_text,
    asset_item_cached_path,
    asset_item_library_asset_id,
    asset_item_preview_path,
    asset_item_preview_reference,
    asset_item_source,
    asset_item_thumbnail_path,
    parse_question_figure_repair_target,
    question_figure_asset_sort_key,
    question_figure_candidate_list,
    question_figure_collection_summary,
    question_figure_compare_display_name,
    question_figure_compare_index_label,
    question_figure_compare_options,
    question_figure_detail_rows,
    question_figure_item_matches_repair_target,
    question_figure_item_summary,
    question_figure_items,
    question_figure_order_value,
    question_figure_payload_matches_item,
    question_figure_target_cache_path,
    question_figure_target_label,
    question_figure_target_value,
)

__all__ = [
    "_asset_item_alt_text",
    "_asset_item_cached_path",
    "_asset_item_library_asset_id",
    "_asset_item_preview_path",
    "_asset_item_preview_reference",
    "_asset_item_source",
    "_asset_item_thumbnail_path",
    "_question_figure_asset_items",
    "_question_figure_asset_sort_key",
    "_question_figure_candidate_list",
    "_question_figure_collection_summary",
    "_question_figure_compare_display_name",
    "_question_figure_compare_index_label",
    "_question_figure_compare_options",
    "_question_figure_detail_rows",
    "_question_figure_item_matches_repair_target",
    "_question_figure_item_summary",
    "_question_figure_order_value",
    "_question_figure_payload_matches_item",
    "_question_figure_repair_target_payload",
    "_question_figure_target_cache_path",
    "_question_figure_target_label",
    "_question_figure_target_value",
    "asset_item_alt_text",
    "asset_item_cached_path",
    "asset_item_library_asset_id",
    "asset_item_preview_path",
    "asset_item_preview_reference",
    "asset_item_source",
    "asset_item_thumbnail_path",
    "parse_question_figure_repair_target",
    "question_figure_asset_sort_key",
    "question_figure_candidate_list",
    "question_figure_collection_summary",
    "question_figure_compare_display_name",
    "question_figure_compare_index_label",
    "question_figure_compare_options",
    "question_figure_detail_rows",
    "question_figure_item_matches_repair_target",
    "question_figure_item_summary",
    "question_figure_items",
    "question_figure_order_value",
    "question_figure_payload_matches_item",
    "question_figure_target_cache_path",
    "question_figure_target_label",
    "question_figure_target_value",
]
