"""
Single Qt binding entrypoint for the repository.

The project standardizes on PySide6 so the repository can follow the same
MIT-source + third-party-notices release posture as V0.2 LTS.
"""

from __future__ import annotations

from PySide6.QtCore import (
    QByteArray,
    QEvent,
    QObject,
    QPoint,
    QPropertyAnimation,
    QRectF,
    QSize,
    QTimer,
    Qt,
    Property,
    Signal,
)
from PySide6.QtGui import (
    QBrush,
    QColor,
    QCursor,
    QFont,
    QIcon,
    QImage,
    QMouseEvent,
    QPainter,
    QPen,
    QPixmap,
)
from PySide6.QtSvg import QSvgRenderer
from PySide6.QtWidgets import (
    QAbstractButton,
    QAbstractItemView,
    QAbstractSlider,
    QAbstractSpinBox,
    QApplication,
    QButtonGroup,
    QCheckBox,
    QColorDialog,
    QComboBox,
    QDialog,
    QDoubleSpinBox,
    QFileDialog,
    QFrame,
    QGraphicsDropShadowEffect,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListView,
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QProgressBar,
    QPushButton,
    QRadioButton,
    QScrollArea,
    QSizeGrip,
    QSizePolicy,
    QSlider,
    QSpinBox,
    QStackedWidget,
    QStyledItemDelegate,
    QTabWidget,
    QTextEdit,
    QToolButton,
    QVBoxLayout,
    QWidget,
)

__all__ = [
    "QAbstractButton",
    "QAbstractItemView",
    "QAbstractSlider",
    "QAbstractSpinBox",
    "QApplication",
    "QButtonGroup",
    "QBrush",
    "QByteArray",
    "QCheckBox",
    "QColor",
    "QColorDialog",
    "QComboBox",
    "QCursor",
    "QDialog",
    "QDoubleSpinBox",
    "QEvent",
    "QFileDialog",
    "QFont",
    "QFrame",
    "QGraphicsDropShadowEffect",
    "QGroupBox",
    "QHBoxLayout",
    "QIcon",
    "QImage",
    "QLabel",
    "QLineEdit",
    "QListView",
    "QListWidget",
    "QListWidgetItem",
    "QMainWindow",
    "QMouseEvent",
    "QObject",
    "QPainter",
    "QPen",
    "QPixmap",
    "QPoint",
    "QProgressBar",
    "Property",
    "QPropertyAnimation",
    "QPushButton",
    "QRadioButton",
    "QRectF",
    "QScrollArea",
    "QSize",
    "QSizeGrip",
    "QSizePolicy",
    "QSlider",
    "QSpinBox",
    "QStackedWidget",
    "QStyledItemDelegate",
    "QSvgRenderer",
    "QTabWidget",
    "QTextEdit",
    "QTimer",
    "QToolButton",
    "Qt",
    "QVBoxLayout",
    "QWidget",
    "Signal",
]
